// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package replay

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *batchStatement) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "query":
			z.Query, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "args":
			err = z.Args.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *batchStatement) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "query"
	err = en.Append(0x82, 0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Query)
	if err != nil {
		err = msgp.WrapError(err, "Query")
		return
	}
	// write "args"
	err = en.Append(0xa4, 0x61, 0x72, 0x67, 0x73)
	if err != nil {
		return
	}
	err = z.Args.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *batchStatement) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "query"
	o = append(o, 0x82, 0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
	o = msgp.AppendString(o, z.Query)
	// string "args"
	o = append(o, 0xa4, 0x61, 0x72, 0x67, 0x73)
	o, err = z.Args.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *batchStatement) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "query":
			z.Query, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "args":
			bts, err = z.Args.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *batchStatement) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Query) + 5 + z.Args.Msgsize()
	return
}

// DecodeMsg implements msgp.Decodable
func (z *natsReplayMessage) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "target_cluster":
			z.TargetCluster, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "TargetCluster")
				return
			}
		case "query":
			z.Query, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "args":
			err = z.Args.DecodeMsg(dc)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		case "timestamp":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "priority":
			z.Priority, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "is_batch":
			z.IsBatch, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "IsBatch")
				return
			}
		case "batch_type":
			z.BatchType, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "BatchType")
				return
			}
		case "batch_statements":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "BatchStatements")
				return
			}
			if cap(z.BatchStatements) >= int(zb0002) {
				z.BatchStatements = (z.BatchStatements)[:zb0002]
			} else {
				z.BatchStatements = make([]batchStatement, zb0002)
			}
			for za0001 := range z.BatchStatements {
				var zb0003 uint32
				zb0003, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "BatchStatements", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "BatchStatements", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "query":
						z.BatchStatements[za0001].Query, err = dc.ReadString()
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001, "Query")
							return
						}
					case "args":
						err = z.BatchStatements[za0001].Args.DecodeMsg(dc)
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001, "Args")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001)
							return
						}
					}
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *natsReplayMessage) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 8
	// write "target_cluster"
	err = en.Append(0x88, 0xae, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.TargetCluster)
	if err != nil {
		err = msgp.WrapError(err, "TargetCluster")
		return
	}
	// write "query"
	err = en.Append(0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
	if err != nil {
		return
	}
	err = en.WriteString(z.Query)
	if err != nil {
		err = msgp.WrapError(err, "Query")
		return
	}
	// write "args"
	err = en.Append(0xa4, 0x61, 0x72, 0x67, 0x73)
	if err != nil {
		return
	}
	err = z.Args.EncodeMsg(en)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	// write "timestamp"
	err = en.Append(0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "priority"
	err = en.Append(0xa8, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Priority)
	if err != nil {
		err = msgp.WrapError(err, "Priority")
		return
	}
	// write "is_batch"
	err = en.Append(0xa8, 0x69, 0x73, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68)
	if err != nil {
		return
	}
	err = en.WriteBool(z.IsBatch)
	if err != nil {
		err = msgp.WrapError(err, "IsBatch")
		return
	}
	// write "batch_type"
	err = en.Append(0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.BatchType)
	if err != nil {
		err = msgp.WrapError(err, "BatchType")
		return
	}
	// write "batch_statements"
	err = en.Append(0xb0, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.BatchStatements)))
	if err != nil {
		err = msgp.WrapError(err, "BatchStatements")
		return
	}
	for za0001 := range z.BatchStatements {
		// map header, size 2
		// write "query"
		err = en.Append(0x82, 0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
		if err != nil {
			return
		}
		err = en.WriteString(z.BatchStatements[za0001].Query)
		if err != nil {
			err = msgp.WrapError(err, "BatchStatements", za0001, "Query")
			return
		}
		// write "args"
		err = en.Append(0xa4, 0x61, 0x72, 0x67, 0x73)
		if err != nil {
			return
		}
		err = z.BatchStatements[za0001].Args.EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "BatchStatements", za0001, "Args")
			return
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *natsReplayMessage) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 8
	// string "target_cluster"
	o = append(o, 0x88, 0xae, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72)
	o = msgp.AppendString(o, z.TargetCluster)
	// string "query"
	o = append(o, 0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
	o = msgp.AppendString(o, z.Query)
	// string "args"
	o = append(o, 0xa4, 0x61, 0x72, 0x67, 0x73)
	o, err = z.Args.MarshalMsg(o)
	if err != nil {
		err = msgp.WrapError(err, "Args")
		return
	}
	// string "timestamp"
	o = append(o, 0xa9, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendInt64(o, z.Timestamp)
	// string "priority"
	o = append(o, 0xa8, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79)
	o = msgp.AppendInt(o, z.Priority)
	// string "is_batch"
	o = append(o, 0xa8, 0x69, 0x73, 0x5f, 0x62, 0x61, 0x74, 0x63, 0x68)
	o = msgp.AppendBool(o, z.IsBatch)
	// string "batch_type"
	o = append(o, 0xaa, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65)
	o = msgp.AppendUint8(o, z.BatchType)
	// string "batch_statements"
	o = append(o, 0xb0, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73)
	o = msgp.AppendArrayHeader(o, uint32(len(z.BatchStatements)))
	for za0001 := range z.BatchStatements {
		// map header, size 2
		// string "query"
		o = append(o, 0x82, 0xa5, 0x71, 0x75, 0x65, 0x72, 0x79)
		o = msgp.AppendString(o, z.BatchStatements[za0001].Query)
		// string "args"
		o = append(o, 0xa4, 0x61, 0x72, 0x67, 0x73)
		o, err = z.BatchStatements[za0001].Args.MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "BatchStatements", za0001, "Args")
			return
		}
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *natsReplayMessage) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "target_cluster":
			z.TargetCluster, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "TargetCluster")
				return
			}
		case "query":
			z.Query, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Query")
				return
			}
		case "args":
			bts, err = z.Args.UnmarshalMsg(bts)
			if err != nil {
				err = msgp.WrapError(err, "Args")
				return
			}
		case "timestamp":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "priority":
			z.Priority, bts, err = msgp.ReadIntBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Priority")
				return
			}
		case "is_batch":
			z.IsBatch, bts, err = msgp.ReadBoolBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "IsBatch")
				return
			}
		case "batch_type":
			z.BatchType, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchType")
				return
			}
		case "batch_statements":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "BatchStatements")
				return
			}
			if cap(z.BatchStatements) >= int(zb0002) {
				z.BatchStatements = (z.BatchStatements)[:zb0002]
			} else {
				z.BatchStatements = make([]batchStatement, zb0002)
			}
			for za0001 := range z.BatchStatements {
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "BatchStatements", za0001)
					return
				}
				for zb0003 > 0 {
					zb0003--
					field, bts, err = msgp.ReadMapKeyZC(bts)
					if err != nil {
						err = msgp.WrapError(err, "BatchStatements", za0001)
						return
					}
					switch msgp.UnsafeString(field) {
					case "query":
						z.BatchStatements[za0001].Query, bts, err = msgp.ReadStringBytes(bts)
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001, "Query")
							return
						}
					case "args":
						bts, err = z.BatchStatements[za0001].Args.UnmarshalMsg(bts)
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001, "Args")
							return
						}
					default:
						bts, err = msgp.Skip(bts)
						if err != nil {
							err = msgp.WrapError(err, "BatchStatements", za0001)
							return
						}
					}
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *natsReplayMessage) Msgsize() (s int) {
	s = 1 + 15 + msgp.StringPrefixSize + len(z.TargetCluster) + 6 + msgp.StringPrefixSize + len(z.Query) + 5 + z.Args.Msgsize() + 10 + msgp.Int64Size + 9 + msgp.IntSize + 9 + msgp.BoolSize + 11 + msgp.Uint8Size + 17 + msgp.ArrayHeaderSize
	for za0001 := range z.BatchStatements {
		s += 1 + 6 + msgp.StringPrefixSize + len(z.BatchStatements[za0001].Query) + 5 + z.BatchStatements[za0001].Args.Msgsize()
	}
	return
}
